# Generated by Django 3.0.7 on 2020-06-07 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='theory.Chapter')),
            ],
            options={
                'unique_together': {('name', 'chapter')},
            },
        ),
        migrations.CreateModel(
            name='SubConcept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subConcepts', to='theory.Concept')),
            ],
            options={
                'unique_together': {('name', 'concept')},
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Theory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theory', models.TextField()),
                ('easyExampleQues1', models.TextField()),
                ('easyExampleQues2', models.TextField()),
                ('easyExampleQues3', models.TextField()),
                ('easyExampleQues4', models.TextField()),
                ('easyExampleQues5', models.TextField()),
                ('easyExampleSol1', models.TextField()),
                ('easyExampleSol2', models.TextField()),
                ('easyExampleSol3', models.TextField()),
                ('easyExampleSol4', models.TextField()),
                ('easyExampleSol5', models.TextField()),
                ('mediumExampleQues1', models.TextField()),
                ('mediumExampleQues2', models.TextField()),
                ('mediumExampleQues3', models.TextField()),
                ('mediumExampleQues4', models.TextField()),
                ('mediumExampleQues5', models.TextField()),
                ('mediumExampleSol1', models.TextField()),
                ('mediumExampleSol2', models.TextField()),
                ('mediumExampleSol3', models.TextField()),
                ('mediumExampleSol4', models.TextField()),
                ('mediumExampleSol5', models.TextField()),
                ('hardExampleQues1', models.TextField()),
                ('hardExampleQues2', models.TextField()),
                ('hardExampleQues3', models.TextField()),
                ('hardExampleQues4', models.TextField()),
                ('hardExampleQues5', models.TextField()),
                ('hardExampleSol1', models.TextField()),
                ('hardExampleSol2', models.TextField()),
                ('hardExampleSol3', models.TextField()),
                ('hardExampleSol4', models.TextField()),
                ('hardExampleSol5', models.TextField()),
                ('difficulty', models.IntegerField()),
                ('importance', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('summary', models.TextField()),
                ('mnemonics', models.TextField(null=True)),
                ('videoUrl', models.CharField(max_length=100)),
                ('targetExam', models.CharField(max_length=100)),
                ('wowTheory', models.TextField()),
                ('wowQues', models.TextField()),
                ('wowReason', models.TextField()),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Theory', to='theory.Concept')),
                ('prerequisites', models.ManyToManyField(related_name='prerequisiteOf', to='theory.SubConcept')),
                ('subConcept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Theory', to='theory.SubConcept')),
                ('twinConcepts', models.ManyToManyField(related_name='twinConceptOf', to='theory.SubConcept')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='theory.Subject'),
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('name', 'subject')},
        ),
    ]
