# Generated by Django 3.0.7 on 2020-06-06 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twin_concept',
            name='twinConceptOf',
        ),
        migrations.AddField(
            model_name='theory',
            name='prerequisites',
            field=models.ManyToManyField(related_name='prerequisiteOf', to='theory.SubConcept'),
        ),
        migrations.AddField(
            model_name='theory',
            name='twinConcepts',
            field=models.ManyToManyField(related_name='twinConceptOf', to='theory.SubConcept'),
        ),
        migrations.DeleteModel(
            name='prerequisite',
        ),
        migrations.DeleteModel(
            name='twin_concept',
        ),
    ]
