# Generated by Django 3.0.7 on 2020-06-06 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theory', '0002_auto_20200606_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theory',
            name='prerequisites',
            field=models.ManyToManyField(null=True, related_name='prerequisiteOf', to='theory.SubConcept'),
        ),
        migrations.AlterField(
            model_name='theory',
            name='twinConcepts',
            field=models.ManyToManyField(null=True, related_name='twinConceptOf', to='theory.SubConcept'),
        ),
    ]
