# Generated by Django 3.0.7 on 2020-06-06 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theory', '0003_auto_20200606_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='theory',
            name='chapter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Theory', to='theory.Chapter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='theory',
            name='prerequisites',
            field=models.ManyToManyField(related_name='prerequisiteOf', to='theory.SubConcept'),
        ),
        migrations.AlterField(
            model_name='theory',
            name='twinConcepts',
            field=models.ManyToManyField(related_name='twinConceptOf', to='theory.SubConcept'),
        ),
    ]
