# Generated by Django 3.0.7 on 2020-06-07 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theory', '0005_auto_20200606_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theory',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='theory',
            name='subject',
        ),
    ]
