# Generated by Django 3.0.7 on 2020-06-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ck',
            name='content',
            field=models.TextField(),
        ),
    ]
