# Generated by Django 3.0.7 on 2020-06-08 07:19

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200608_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ck',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
